(setq load-path (cons "/usr/local/Cellar/erlang/19.1/lib/erlang/lib/tools-2.8.6/emacs" load-path))
(setq erlang-root "/usr/local/Cellar/erlang/19.1/lib/erlang")
(setq exec-path (cons "/usr/local/bin" exec-path))
(require 'erlang-start)
(add-hook 'erlang-mode-hook 'auto-complete-mode)
